JointController:
    type: JointController/JointController
    # panda_urdf: /home/hcilab/Documents/DroneCamera/src/drone-panda/urdfs/panda.urdf
    panda_urdf: /home/hcilab/Documents/DroneCamera/src/drone-panda/urdfs/lio.urdf
    lowpass_cutoff:
        2

    force_response_gain:
        0.01
    
    k_gains:
        - 1200.0
        - 1000.0
        - 1000.0
        - 800.0
        - 300.0
        - 200.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0

    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    
    home_position:
        - 0.0
        - 0.0
        - 0.0 
        - -1.5
        - 0.0
        - 1.5
        - 0.785

    joint_min:
        - -2.8973
        - -1.7628
        - -2.8973
        - -3.0718
        - -2.8973
        - -0.0175
        - -2.8973
    
    joint_max:
        - 2.8973
        - 1.7628
        - 2.8973
        - -0.0698
        - 2.8973
        - 3.7525
        - 2.8973
    
    joint_vel_max:
        - 1.9 #2.1750
        - 1.9 #2.1750
        - 1.9 #2.1750
        - 1.9 #2.1750
        - 2.4 #2.6100
        - 2.4 #2.6100
        - 2.4 #2.6100
    
    joint_accel_max:
        - 6 #15
        - 5  #7.5
        - 5  #10
        - 6 #12.5
        - 10 #15
        - 13 #20
        - 13 #20

    joint_jerk_max:  
        - 1000 #800  #7500
        - 1000 #400  #3750
        - 1000 #500  #5000
        - 1000 #600  #6250
        - 1000 #700  #7500
        - 1000 #1400  #10000
        - 1000 #1400  #10000
