up_translation: -0.052 0 0.052 #-0.052 CHANGED BY SHALUTHA
up_rotation: 0 -1.57 3.14

left_finger_translation: 0.0645 0 0.052
left_finger_rotation: 0 0 0
# Set to '', if the finger has no tip.
left_tip_translation: ''

right_finger_translation: 0.0645 0 0.052
right_finger_rotation: 0 0 0
# Set to '', if the finger has no tip.
right_tip_translation: ''

# 0.189 0 0.052
tcp_translation: 0.189 0 0.052
tcp_rotation: 0 0 0

lower_angle_limit: 0
upper_angle_limit: 30.0
velocity_limit: 60.0
effort_limit: 50