#!/usr/bin/env python
import rospy
from geometry_msgs.msg import Vector3, PoseStamped, Twist
import numpy as np
import sys
import time
import copy

def movePanda():
    rospy.init_node('panda_mover')
    ikpub = rospy.Publisher('/panda_ik/input', PoseStamped, queue_size=1)
    freq = 1000
    rate = rospy.Rate(freq) # 1000hz

    pose = PoseStamped()
    pose.header.frame_id="panda_gripper_joint"
    pose.pose.orientation.w = 1.0
    pose.pose.orientation.x = 0.0
    pose.pose.orientation.y = 0.0
    pose.pose.orientation.z = 0.0
    time.sleep(1)

    for ii in range(0,6000):
        pose.header.stamp = rospy.Time.now()
        pose.pose.position.x = np.abs(0.5*np.cos(ii/2000))
        pose.pose.position.y = 0.5*np.sin(ii/2000)
        pose.pose.position.z = 0.2
        ikpub.publish(pose)
        rate.sleep()

    for ii in range(0,6000):
        pose.header.stamp = rospy.Time.now()
        pose.pose.position.x = np.abs(0.5*np.cos(ii/1000))
        pose.pose.position.y = 0.5*np.sin(ii/1000)
        pose.pose.position.z = 0.2
        ikpub.publish(pose)
        rate.sleep()
    
    for ii in range(0,1000):
        pose.header.stamp = rospy.Time.now()
        pose.pose.position.x = 0.5
        pose.pose.position.y = 0
        pose.pose.position.z = 0.2
        ikpub.publish(pose)
        rate.sleep()

if __name__ == '__main__':
    movePanda()


