#!/usr/bin/env python

""" Runs tello driver through subprocess
 Created: 2/9/2022
"""

__author__ = "Mike Hagenow"

import rospy
import time
import signal
from std_msgs.msg import String, Float64
from sensor_msgs.msg import PointCloud2
import numpy as np
import rospkg
import subprocess32

class TelloLauncher:
    def __init__(self):
        rospy.init_node('tello_launcher')
        self._p = None
        signal.signal(signal.SIGINT, self.signal_handler)

        # Subscribe to start/stop mapping
        rospy.Subscriber("rvizToggle", String, self.mappingToggle)
        

    def shutdown(self):
        if self._p is not None:
            self._p.terminate()  

    def signal_handler(self, sig, frame):
        if self._p is not None:
            self._p.terminate() 
        sys.exit(0)

    def mappingToggle(self,data):
        if data.data == "tello":
            self.startTello()

    def startTello(self):
        if self._p is not None:
            self._p.terminate() 
        self._p = subprocess32.Popen(["roslaunch", "drone_panda", "tello.launch"])
        

       
if __name__ == "__main__":
    tello = TelloLauncher()
    rospy.spin()
    tello.shutdown()






