set(_CATKIN_CURRENT_PACKAGE "panda_ik")
set(panda_ik_VERSION "0.1.1")
set(panda_ik_MAINTAINER "Kevin Welsh <kpwelsh@cs.wisc.edu>")
set(panda_ik_PACKAGE_FORMAT "2")
set(panda_ik_BUILD_DEPENDS "message_generation" "eigen" "message_runtime" "drone_ros_msgs" "geometry_msgs" "realtime_tools" "roscpp" "tf2" "tf2_ros")
set(panda_ik_BUILD_EXPORT_DEPENDS "message_runtime" "geometry_msgs" "realtime_tools" "roscpp" "tf2" "tf2_ros")
set(panda_ik_BUILDTOOL_DEPENDS "catkin")
set(panda_ik_BUILDTOOL_EXPORT_DEPENDS )
set(panda_ik_EXEC_DEPENDS "message_runtime" "rospy" "drone_ros_msgs" "geometry_msgs" "realtime_tools" "roscpp" "tf2" "tf2_ros")
set(panda_ik_RUN_DEPENDS "message_runtime" "rospy" "drone_ros_msgs" "geometry_msgs" "realtime_tools" "roscpp" "tf2" "tf2_ros")
set(panda_ik_TEST_DEPENDS )
set(panda_ik_DOC_DEPENDS )
set(panda_ik_URL_WEBSITE "")
set(panda_ik_URL_BUGTRACKER "")
set(panda_ik_URL_REPOSITORY "")
set(panda_ik_DEPRECATED "")