footprint: [[0.15,-0.29],[-0.7,-0.29],[-0.7,0.29],[0.15,0.29]]

sensors:
  lidar:
    -
      name: lidar_front
      portname: /dev/flashlidar_front
      name_for_costmap: [flashlidar]
      type_for_costmap: [LaserScan]
      topic_for_costmap: ['/scan_front']
      marking: [true]
      clearing: [true]
      expected_update_rate: [0]
      offset_x: 0.08202
      offset_y: 0.0
      offset_z: -0.01
      offset_roll: 0
      offset_pitch: 3.14
      offset_yaw: 0
    -
      name: lidar_back
      portname: /dev/flashlidar_back
      name_for_costmap: [flashlidar_back]
      type_for_costmap: [LaserScan]
      topic_for_costmap: ['/scan_back']
      marking: [true]
      clearing: [true]
      expected_update_rate: [0]
      offset_x: -0.41803
      offset_y: 0.0
      offset_z: -0.01
      offset_roll: 0
      offset_pitch: 3.14
      offset_yaw: 3.14


